### ISSUE TITLE
Support lsp over tcp

### ISSUE THREAD

**Issue by ghost** [orbitalquark/textadept-lsp#12]
Regarding LSP, I will very glad if TextAdept could support LSP over TCP. This language server only operates over TCP:

https://github.com/objeck/objeck-lsp

Currently there are only two options to use with it as I know: Sublime Text or VSCode :face_exhaling:

**Comment by orbitalquark** [comment]
This would involve importing the LuaSocket library, and enabling passive listening for incoming socket data. There is a lot of complexity here that Qt and GTK abstract away with their I/O channel routines. If I ever run into a server I need that only communicates over sockets, then I may work on this. Otherwise, I cannot justify the effort right now :(
